version: '3'

services:
  nginx:
    build: .
    restart: always
    env_file:
        - ./ENVS
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_secrets:/etc/letsencrypt
    networks: 
      - closed_network

volumes:
  nginx_secrets:
