# Config file for the "Stale" GitHub application: https://github.com/apps/stale
# Will close comments/pull requests if they are inactive for too long.
daysUntilStale: 60
daysUntilClose: 7
exemptLabels:
  - pinned
  - security
staleLabel: wontfix
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs. Thank you
  for your contributions.
closeComment: false
