version: '3'

services:
  nginx:
    build: .
    restart: unless-stopped
    environment:
      - CERTBOT_EMAIL
      - STAGING
      - DHPARAM_SIZE
      - RSA_KEY_SIZE
      - RENEWAL_INTERVAL
    env_file:
      - ./nginx-certbot.env
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_secrets:/etc/letsencrypt

volumes:
  nginx_secrets:
