name: "build-tags"

on:
  push:
    branches-ignore:
      - "**"
    tags:
      - "v[1-9].[0-9]+.[0-9]+-nginx[1-9].[0-9]+.[0-9]+"

jobs:
  docker_buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Extract version numbers from GitHub reference
        id: tagger
        run: bash .github/version_extractor.sh ${GITHUB_REF}

      - name: Set up QEMU environment
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push all images
        uses: docker/build-push-action@v2
        with:
          context: ./src
          platforms: |
            linux/amd64
            linux/386
            linux/arm64
            linux/arm/v7
          pull: true
          no-cache: true
          push: true
          build-args: BUILDX_QEMU_ENV=true
          tags: |
            jonasal/nginx-certbot:${{ steps.tagger.outputs.APP_MAJOR }}
            jonasal/nginx-certbot:${{ steps.tagger.outputs.APP_MAJOR }}.${{ steps.tagger.outputs.APP_MINOR }}
            jonasal/nginx-certbot:${{ steps.tagger.outputs.APP_MAJOR }}.${{ steps.tagger.outputs.APP_MINOR }}.${{ steps.tagger.outputs.APP_PATCH }}
            jonasal/nginx-certbot:${{ steps.tagger.outputs.APP_MAJOR }}.${{ steps.tagger.outputs.APP_MINOR }}.${{ steps.tagger.outputs.APP_PATCH }}-nginx${{ steps.tagger.outputs.NGINX_VERSION }}
